{% set name = "spglib" %}
{% set version = "2.7.0" %}
{% set sha256 = "b22fc9abae9716c574fbc6d55cfc53ed654a714fccc5657a26ff5d18114bd8bd" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-","") }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spglib/spglib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports: spglib  # [not win]
  # Build is currently failing for pypy and aarch64 or ppc64le due to a rpath issue:
  skip: true  # [((python_impl == 'pypy') and (aarch64 or ppc64le)) or py<39]

requirements:
  build:
    # cross-python needed to run $PYTHON -m pip on build
    # Otherwise it gets Bad CPU type in executable
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - gtest
    - cmake
    - ninja
  host:
    - python
    - numpy
    # These are technically `build` requirements, but conda build fails if put there
    - pip
    - scikit-build-core
    - setuptools-scm
    - pybind11
  run:
    - python
    - typing-extensions
    - importlib-resources

test:
  requires:
    - pyyaml
    - pytest
  imports:
    - spglib
  source_files:
    - pyproject.toml
    - test/functional/python
  commands:
    - pytest


about:
  home: https://spglib.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Space symmetry groups spglib module/library.


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://spglib.readthedocs.io
  dev_url: https://github.com/spglib/spglib

extra:
  recipe-maintainers:
    - LecrisUT
    - jochym
    - atztogo
