{% set name = "spglib" %}
{% set version = "2.0.2" %}
{% set sha256 = "10e44a35099a0a5d0fc6ee0cdb39d472c23cb98b1f5167c0e2b08f6069f3db1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spglib/spglib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports: spglib  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - python
    - numpy
    - pip
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pyyaml
    - pytest
  imports:
    - spglib
  source_files:
    - python/test
  commands:
    - pytest


about:
  home: https://spglib.github.io/spglib/
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ RECIPE_DIR }}/COPYING
  summary: Space symmetry groups spglib module/library.


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://spglib.github.io/spglib/
  dev_url: https://github.com/spglib/spglib

extra:
  recipe-maintainers:
    - jochym
    - atztogo
