{% set name = "spglib" %}
{% set version = "2.1.0" %}
{% set sha256 = "31bca273a1bc54e1cff4058eebe7c0a35d5f9b489579e84667d8e005c73dcc13" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-","") }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/spglib/spglib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports: spglib  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - gtest
    # TODO: Remove gmock. We are only using gtest, but conda package requires gmock for gtest
    - gmock
    - cmake
    - ninja
    - scikit-build-core
  host:
    - python
    - numpy
    - pip
    - setuptools
    - scikit-build-core
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pyyaml
    - pytest
  imports:
    - spglib
  source_files:
    - pyproject.toml
    - test/functional/python
  commands:
    - pytest


about:
  home: https://spglib.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ RECIPE_DIR }}/COPYING
  summary: Space symmetry groups spglib module/library.


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://spglib.readthedocs.io
  dev_url: https://github.com/spglib/spglib

extra:
  recipe-maintainers:
    - LecrisUT
    - jochym
    - atztogo
