{% set name = "spglib" %}
{% set version = "1.16.2" %}
{% set sha256 = "5723789bee7371ebba91d78c729d2a608f198fad5e1c95eebe18fda9f2914ec8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/atztogo/spglib/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  run_exports: spglib  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - cmake
  host:
    - python
    - numpy
    - pip
    - setuptools
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pyyaml
  imports:
    - spglib
  source_files:
    - python/test
  commands:
    - python -m unittest discover -b -s python/test


about:
  home: https://atztogo.github.io/spglib/
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ RECIPE_DIR }}/COPYING
  summary: Space symmetry groups spglib module/library.


  description: |
    Spglib is a library for finding and handling crystal symmetries.
  doc_url: https://atztogo.github.io/spglib/
  dev_url: https://github.com/atztogo/spglib

extra:
  recipe-maintainers:
    - jochym
    - atztogo
